# ------------------------------------------------------------------------------

- name: Playbook to Install Docker
  hosts: all
  become: true

  tasks:

    - name: Install Docker
      ansible.builtin.package:
        name: "{{ 'docker.io' if ansible_facts.os_family == 'Debian' else 'docker' }}"
        state: present
