# ------------------------------------------------------------------------------

- name: Verify Docker Prerequisites
  hosts: all

  tasks:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Verify service is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services['docker.service'].state == 'running'
        fail_msg: "docker is not running"
        success_msg: "docker is running"

# ------------------------------------------------------------------------------

- name: Setup Python Virtual Environment
  hosts: all

  tasks:

    - name: Install python packages
      ansible.builtin.pip:
        name:
          - requests
          - docker
        state: present
        virtualenv: "{{ ansible_facts.env.HOME }}/.playbook/swarm/venv"
        virtualenv_command: python3 -m venv
